### ISSUE TITLE
ITU-T T.35 messages can be both prefix and postfix. 

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#101]
The current text includes the following sentence in section 6.5.

The film grain parameters signaled in this metadata message are applied to the output video picture that is associated with the coded video picture that follows the current metadata message in the encoded video bitstream.

However, in MPEG specifications, the ITU-T T.35 SEI message can appear both as postfix and prefix. If the message appears postfix, the above sentence would mean that the grain should be applied to the next frame, not the current. The above sentence is also a bit problematic given the nature of prediction in the metadata. Not all parameters are used but only a single set. The above sentence does not distinguish this, and feels incorrect. Note also this breaks the use of the T.35 mechanism at the system layer, since there the metadata is not carried in the encoded video bitstream but in a system track.

Maybe a better sentence could be the following.

"During decoding a specific film grain parameter set is associated with each decoded picture and this information is utilized to apply film grain as indicated in this specification."

We can keep silent at this stage. If we want to say something we could simple say "How a film grain parameter set is associated with each decoded picture is outside the scope of this specification".

**Comment by andrey-norkin** [comment]
This was addressed
