### ISSUE TITLE
On trailing bits

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/afgs1-spec#24]
This following note includes a shall.

> Note: The last byte of the valid content of the data is considered to be the last byte that is not equal to zero. This rule is to prevent the dropping of valid bytes by systems that interpret trailing zero bytes as a padding continuation of the trailing bits. This implies that when any payload data is present, at least one byte of the payload data (including the trailing bit) shall not be equal to 0.

I personally don't understand why trailing bits are needed in AV1 but that ship has sailed. For this spec let's maybe not put normative constraints and make it flexible enough to allow usage without such a constraint in other codecs that might not have such a requirement. The `av1_film_grain_param_sets` could have something like that but for future work let's not make it mandatory.

**Comment by andrey-norkin** [comment]
Closed since the pull request was accepted.
