### ISSUE TITLE
On AOMedia metadata registry

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/afgs1-spec#26]
I was a bit confused about this note:

> Note: This specification only provides the value of the itu_t_t35_terminal_provider_oriented_code that identifies the av1 film grain parameters metadata. The complete syntax of aom_itu_t_t35_payload( ) and the list of values for AOMedia itu_t_t35_terminal_provider_oriented_code are defined in the [AOMedia metadata registry](https://aomediacodec.github.io/metadata-registry/) specification.

because this spec actually defines the syntax for the generic AOM T.35 payload. Perhaps the idea would be to move the syntax proposed in https://github.com/AOMediaCodec/afgs1-spec/issues/22 to that [AOMedia metadata registry](https://aomediacodec.github.io/metadata-registry/) specification?

**Comment by andrey-norkin** [comment]
This was fixed in #19
