### ISSUE TITLE
On element prefix for syntax elements

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/afgs1-spec#27]
🤔  would it be better if we would use a prefix in front of each syntax element within the `av1_film_grain_params`? 

For example, instead of `bit_depth` you would define it as `av1fg_bit_depth` and so on.
I think it would help to avoid possible misunderstandings in future because there is quite some overlap with AV1.

**Comment by andrey-norkin** [comment]
It was discussed. In general, it was considered a good idea. However, it was agreed that it is tool late to make such extensive changes that late in the specification development
