### ISSUE TITLE
On the placement of the FGS metadata in the elementary stream

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/afgs1-spec#28]
Maybe I missed this but I didn't see any details on the placement of the FGS metadata OBU and on the number of FGS metadata OBUs. 

Is it present just once in a temporal unit? Does it come after the frame header OBU or before it? What if there are multiple frames with show_frame=0 in a single TU? and so on.

**Comment by podborski** [comment]
> apply_grain equal to 1 specifies that film grain should be added to this frame. apply_grain equal to 0 specifies that film grain should not be added.

What is `this frame`?

**Comment by andrey-norkin** [comment]
This was discussed, and it was agreed that the current specification should be silent on that. Instead, this should be defined by an elementary bitstream, in which this metadata is included.
