### ISSUE TITLE
Improve scope

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/afgs1-spec#52]
The current scope reads:
> This document provides the metadata format and bit-accurate specification for the standalone AOMedia film grain synthesis technology. This technology is based on the film grain modeling process that is specified in the AV1 specification. However, it permits the same model to be applied on other video coding specifications using ITU-T T.35 signaling.

It has the following issues:
- The term "metadata format" is unclear. "metadata" is a loaded term and it is not defined in this document
- "bit-accurate specification". What does it mean? The term "bit-accurate" is not used in AV1 for example.
- "standalone". It is used in the abstract and scope but not defined.
- The relationship to AV1 should be clarified.

I suggest something along the lines of:
> This document specifies: a film grain synthesis process, and a corresponding a binary format for representing and transmitting its parameters. The binary format is intended to be transported in structures of elementary streams that permit embedding data non-essential for decoding, sometimes referred to as metadata or supplemental information. In particular, it is meant to be carried in ITU-T T.35 messages. This specification is based on the film grain modeling process that is specified in the AV1 specification, but differs in the following way: the binary syntax is different and not backwards compatible; however, once decoded, the processing model is backwards compatible in that the extra parameters that are not defined in AV1 can be ignored and the AV1 processing module will produce an acceptable result.

**Comment by andrey-norkin** [comment]
This was addressed in #55
