### ISSUE TITLE
conformance constrain should be also about CICP parameters, not just resolution

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#69]
In the spec we currently have that:

For a given decoded picture, there shall not be more than one film grain parameter set for a given
combination of luma horizontal and luma vertical resolution.

However, is it not more appropriate to have a condition that says:

For a given decoded picture, there shall not be more than one film grain parameter set for a given
combination of luma horizontal resolution, luma vertical resolution,  subsampling_x, subsampling_y, color_primaries,  transfer_characteristics, matrix_coefficients, and video_full_range_flag.

I am skipping bitdepth since likely that is not important.

With the above constraint, for example, what would happen if we wish to indicate a different colour representation from what is in the decoded frame? We would only be able to do that for a different resolution and not for the decoded resolution. That seems an omission and my understanding was that the rule should be covering the full set, not just resolution. Did we forget to update this?

**Comment by andrey-norkin** [comment]
It was previously discussed that the CICP is informative and should match the decoded picture. Allowing it to take different values from the decoded picture would mean expanding the scope.

**Comment by andrey-norkin** [comment]
This was addressed
