### ISSUE TITLE
Display persistence hinted by a note in the semantics.

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#70]
We have the following note in the text:

**Note:** In the case of update_grain_flag being equal to 0, the film grain synthesis module should use the parameters
from the previous frame in the display order and not the coding order.

That seems wrong since it suggests some form of display persistence. Persistence should be based on the referencing process. 

I would suggest removing this note altogether.

**Comment by andrey-norkin** [comment]
It is removed in #73
