### ISSUE TITLE
ISO and ITU-T specs use "Colour" and not "Color"

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#72]
The document has the following statement:

The integer value is defined by the “Color primaries” section of ISO/IEC 23091-4 and/or ITU-T H.273.  

Given that these specs do not use "Color" but "Colour", one might not be able to find the above section. Maybe, if we wish to stick with "color", we could say "by the corresponding color primaries section of...." without any type of quotes. Giving a hint that this is a title is problematic.

**Comment by andrey-norkin** [comment]
It was agreed to use spelling "color" in the specification
