### ISSUE TITLE
What happens with missing CICP information if a codec switches CICP information at the picture level?

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#74]
As the title suggests, it is quite possible that a future codec may include the capability of having different CICP information for each frame. 

Now, what happens if we indicate several sets without CICP information in a first frame. Do these take the CICP information of that frame (even if that is not used)? In that case if another frame uses different CICP information, would that mean that the parameters would have to be resent? Or the CICP information is silent and just takes the values corresponding to the CICP parameters of the picture that activates them (so they are dynamic?).

**Comment by andrey-norkin** [comment]
What is a possible application? The only one that comes in mind is having some sort of scalability in the color space domain. But in this case,  the change is likely to be between the base and enhancement layers.

**Comment by andrey-norkin** [comment]
This was addressed
