### ISSUE TITLE
Need a resitrction that film_grain_param_set_idx and film_grain_param_set_idx_for_prediction in a set should be different

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#75]
It seems we have an interesting issue. The current spec does not say whether film_grain_param_set_idx_for_prediction is disallowed to be different from film_grain_param_set_idx. We need a conformance requirement that the values are different.

**Comment by andrey-norkin** [comment]
This seems already addressed in the specification

**Comment by andrey-norkin** [comment]
This is already addressed in the specification
