### ISSUE TITLE
Conformance seems not needed in the decoding section

### ISSUE THREAD

**Issue by alexismt73** [AOMediaCodec/afgs1-spec#78]
We currently have the following text, which seems unnecessary and should be removed. Why is this even needed? This is not about AV1 conformance but about the ability to utilize the metadata for film grain synthesis. We can keep silent about conformance.

===
When film_grain_params_present is equal to 1, a conformant AV1 film grain synthesis module shall satisfy at least one of the
following two options:

  1. A conformant AV1 film grain synthesis module shall produce output pictures that are identical in all respects and have the same output order as those produced by the AV1 film grain synthesis process specified herein including applying the exact film grain synthesis process as specified in [section 8.2][].

  2. A conformant AV1 film grain synthesis module shall produce output pictures that are in the same order and do not have perceptually
  significant differences with the pictures produced by the reference film grain synthesis process specified in [section 8.2][]
  when applied to the input pictures of the film grain synthesis process with the film grain parameters signaled for these pictures.
  The definition of "perceptually significant differences" is beyond the scope of this specification and may be specified,
  for example, by a service provider as part of their accreditation program.
  The film grain synthesis process applied by a conformant AV1 film grain synthesis module should be feature complete with regards to
  the reference film grain synthesis process of [section 8.2][] including scaling strength of the film grain
  as a function of intensity according to the signaled parameters, same maximum AR lag, and similar
  modeling of correlation between luma and chroma and smoothing of transitions between blocks of grain when applicable.

**Note:** To ensure conformance, film grain module manufacturers are advised to implement the film grain synthesis
process as specified in [section 8.2][].
One reason to choose the second conformance option is implementation of optional processing steps
before input or after the output of [section 7.18.2][] and the film grain synthesis process, in which case there could be minor differences in the output with the reference film grain synthesis process of [section 8.2][]. Examples of these optional processing steps are algorithms improving output picture quality, such as de-banding filtering and coding artefacts removal.
{:.alert .alert-info }

**Comment by andrey-norkin** [comment]
It was agreed in the FG7 call that the conformance section is desirable

**Comment by andrey-norkin** [comment]
Discussed and conformance section updated
